---

- hosts: all
  become: true

  tasks:

  - name: [Ubuntu] install apache and php
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: [Fedora] install apache and php
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"
