---

- hosts: all
  become: true

  pre_tasks:
  - name: install updates (Fedora)
    dnf:
      update_only: yes
      update_cache: true
    when: ansible_distribution == "Fedora"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true

  tasks:
  - name: (Ubuntu) install apache and php
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: (Fedora) install apache and php
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"


- hosts: db_servers
  become: true

  tasks:

  - name: install mariadb package (Fedora)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Fedora"
  
  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true

  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
