- name: mariadb package (Ubuntu)
  tags: ubuntu, db, mariadb
  package:
    name: "{{ mariadb_server }}"
    state: latest

- name: start and enable mariadb service
  tags: mariadb, fedora
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: yes
  when: ansible_distribution == "Fedora"
