- name: install unzip
  package:
    name: unzip

- name: install terraform from zip repositorry
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.6.4/terraform_1.6.4_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
